### ISSUE TITLE
Поддержка в протоколе Modbus ответов об ошибках

### ISSUE THREAD

**Issue by unreal79** [vladimkov/Terminal_by_Koval#2]
В настоящее время Терминал не "понимает" ответов об ошибках от Modbus-устройства. Формат ответа простой:
5-тибайтовое сообщение. К номеру функции прибавляется 0x80 (см. раздел 7 «MODBUS Exception Responses» из «MODBUS Application Protocol Specification V1.1b3»).

**Comment by vladimkov** [comment]
добавлено в версии 2.98
