### ISSUE TITLE
Нечитабельные надписи

### ISSUE THREAD

**Issue by unreal79** [vladimkov/Terminal_by_Koval#3]
Некоторые надписи нечитабельны: буквы сливаются в "толстые" пиксели. Скриншот по ссылке: https://prnt.sc/26fi2z1

Windows 7 64bit, масштабирование 125% (Панель управления\Все элементы панели управления\Экран), разрешение 1920х1080.

**Comment by vladimkov** [comment]
Здравствуйте, мне не удаётся у себя повторить эффект, показанный на скриншоте, при 125% масштабировании надписи отображаются корректно. Все нечитабельные надписи, указанные Вами, выполненные фонтом "Small Fonts". Возможно у Вас в системе он не установлен и Windows подменила его ближайшим похожим?
